print('Want to hear some jokes?')
input('')
print('How does a computer get drunk?')
input('')
print('It takes too many screenshots!')
print('')
print('')
print('Ready for the next joke?')
input('')
print('What do you get when you cross an Elephant with a Rhino?')
input('')
print('Eleph-I-no!')
print('')
print('')
print('One more joke?')
input('')
print('What do you call a dinosaur fart?')
input('')
print('A blast from the past!')
print('')
print('')
print('Wocka, wocka! I hope you laughed!')
print('Press Enter to close.')
input('')
print('')